### ISSUE TITLE
[cupertino_icons] version 1.0.1 requires Dart Sdk 1.12.0

### ISSUE THREAD

**Issue by prateek-aher** [ritvij14/flutter-pokedex#1]
![image](https://user-images.githubusercontent.com/47930146/107139445-2df8c180-6941-11eb-8fe6-a6080918fecb.png)
I'm using the stable channel. 
On this release, Latest Dart SDK is on 2.10.5 version which supports cupertino_icons dependency up to 1.0.0
Which channel did you use?

**Comment by ritvij14** [comment]
> ![image](https://user-images.githubusercontent.com/47930146/107139445-2df8c180-6941-11eb-8fe6-a6080918fecb.png)
> I'm using the stable channel. 
> On this release, Latest Dart SDK is on 2.10.5 version which supports cupertino_icons dependency up to 1.0.0
> Which channel did you use?

I used the beta channel. The one which has flutter web in it as well. 🤔

**Comment by prateek-aher** [comment]
Oh! This is a web app. I assumed it would be a mobile app.

**Comment by ritvij14** [comment]
> Oh! This is a web app. I assumed it would be a mobile app.

Actually, it's a mobile app as well. If u switch your channels and then run it, it will run on your phone as a normal app too. The thing is if you add the Flutter web thing, you can debug your app in chrome itself as a web app. That makes my work faster that's why I do it that way.

Though running as a web app is not that good sometimes, for example in this project I could not see images of pokemon on web app as there is some bug in the `NetworkImage`.

**Comment by prateek-aher** [comment]
You should include that in README.md

**Comment by ritvij14** [comment]
> You should include that in README.md
> 

Yeah, good idea, will do it.
